config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users
  resources :promotions, only: %i[index show new create edit update destroy] do
    member do
      post 'generate_coupons'
      post 'approve'
    end
  end

  resources :coupons, only: [:index] do
    post 'inactivate', on: :member
    get 'search', on: :collection
  end

  namespace 'api', defaults: { format: :json } do
    namespace 'v1' do
      resources :coupons, only: [:show]
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  belongs_to :promotion
  validates :code, uniqueness: true
  
  enum status: { active: 0, inactive: 5 }
end

app/models/payment_method.rb
class PaymentMethod
  attr_reader :name, :code

  def initialize(name:, code:)
    @name = name
    @code = code
  end

  def self.all
    response = Faraday.get('pagamentos.com.br/api/v1/payment_methods')
    return [] if response.status == 403 #Guard Clause

    json_response = JSON.parse(response.body, symbolize_names: true)

    json_response.map { |r| new(name: r[:name], code: r[:code]) }
  end
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  has_many :product_category_promototions
  has_many :promotions, through: :product_category_promototions
end

app/models/product_category_promototion.rb
class ProductCategoryPromototion < ApplicationRecord
  belongs_to :product_category
  belongs_to :promotion
end

app/models/promotion.rb
class Promotion < ApplicationRecord
  has_secure_token :token, length: 65

  has_one_attached :photo
  has_many :coupons
  has_one :promotion_approval

  has_many :product_category_promototions
  has_many :product_categories, through: :product_category_promototions

  belongs_to :user

  validates :name, :code, :discount_rate, :coupon_quantity, :expiration_date, presence: true
  validates :code, uniqueness: true
  validate :generated_coupons, on: :update


  def generate_coupons!
    codes_coupons = []
    Coupon.transaction do
      (1..coupon_quantity).each do |number|
        codes_coupons << { code: "#{code}-#{'%04d' % number}", created_at:Time.now, updated_at:Time.now }
      end
      coupons.insert_all(codes_coupons)
    end
  end

  def approve!(approval_user)
    PromotionApproval.create(promotion: self, user: approval_user)
  end

  def approved?
    promotion_approval
  end

  def approved_at
    promotion_approval&.approved_at

    return nil unless promotion_approval
    promotion_approval.approved_at
  end

  def approver
    promotion_approval&.user
  end

  private

  def generated_coupons
    if coupons.any?
      errors.add(name,'não pode ser alterado. Pois os cupons já foram gerados.')
    end
  end
end

app/models/promotion_approval.rb
class PromotionApproval < ApplicationRecord
  belongs_to :promotion
  belongs_to :user

  validate :different_user

  private

  def different_user
    if promotion && promotion.user == user
      errors.add(:user, 'não pode ser o criador da promoção')
    end
  end
end

app/models/random_word.rb
class RandomWord
  def self.random
    if Random.rand < 0.5
      'Campus'
    else
      'Code'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/api_controller.rb
class Api::V1::ApiController < ActionController::API
end

app/controllers/api/v1/coupons_controller.rb
class Api::V1::CouponsController < ActionController::API
  def show
    coupon = Coupon.find_by(code: params[:id])
    return render status: 404, json: "{msg: 'coupon not found'}" if coupon.nil?
    render json: coupon.as_json(only: [:code, :status],
                                include: {
                                  promotion:{only: :discount_rate}
                                }), status: 200
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  before_action :set_coupon, only: %i[inactivate]

  def index
    @coupons = Coupon.all
  end

  def search
    @coupons = Coupon.where('code LIKE ?', "%#{params[:q]}%")
    render json: @coupons
  end

  def inactivate
    @coupon.inactive!
    #raise Error if @coupon Entender depois pq isso quebrou
    redirect_to @coupon.promotion
  end

  private

  def set_coupon
    @coupon = Coupon.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
  before_action :set_promotion, only: %i[show edit update destroy generate_coupons approve]
  before_action :authenticate_user!

  def index
    @promotions = Promotion.all
  end

  def new
    @promotion = Promotion.new
    @product_categories = ProductCategory.all
    #@payment_methods = PaymentMethod.all
  end

  def create
    @promotion = Promotion.new(promotion_params)
    @promotion.user = current_user

    if @promotion.save
      redirect_to @promotion, notice: 'Promotion was successfully created.'
    else
      @product_categories = ProductCategory.all
      render :new ,notice: 'Promotion could not be created.'
    end
  end

  def show; end

  def edit
    @product_categories = ProductCategory.all
  end

  def update
    if @promotion.update(promotion_params)
      redirect_to @promotion, notice: 'Promotion was successfully updated.'
    else
      @product_categories = ProductCategory.all
      render :edit
    end
  end

  def destroy
    @promotion.destroy

    redirect_to promotions_path
  end

  def generate_coupons
    @promotion.generate_coupons!
    redirect_to @promotion, notice: t('.success')
  end

  def approve
    @promotion.approve!(current_user)
    PromotionMailer.notify_approval(@promotion.id).deliver_now
    redirect_to @promotion
  end

  private

  def set_promotion
    @promotion = Promotion.find(params[:id])
  end

  def promotion_params
    params.require(:promotion).permit(:name, :description,:code,:discount_rate,:coupon_quantity,
                                      :expiration_date,product_category_ids:[])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/coupons/_coupon.html.erb
<%= coupon.code%>

app/views/coupons/index.html.erb
<%= form_with url: search_coupons_path, method: :get, local: false, id: 'search-form' do |f| %>
  <%= f.label :q, 'Termo' %>
  <%= f.text_field :q %>
  <%= f.submit 'Buscar' %>
<% end %>

<div id='coupons'>
  <%= render @coupons %>
</div>

<%= content_for :javascript do %>
  <%= javascript_pack_tag 'search' %>
<% end %>

app/views/coupons/search.js.erb
var couponsDiv = document.querySelector('#coupons')
couponsDiv.innerHTML = '<%= j(render @coupons) %>'

app/views/home/index.html.erb
<h1>Promotion System</h1>
<p>Boas vindas ao sistema de gestão de promoções</p>

<%= link_to 'Promoções', promotions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PromotionSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>

      <% if user_signed_in? %>
        <%= current_user.email %>
        <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
        <%= link_to 'Cupons', coupons_path %>
      <% else %>
        <%= link_to 'Entrar', new_user_session_path%>
      <% end %>
    </nav>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

  <%= yield :javascript %>
  </body>
</html>

app/views/promotions/_form.html.erb
<% if promotion.errors.any? %>
  <p>Não foi possível criar a promoção</p>
  <p>Confira os erros abaixo:</p>
  Erros: <%= promotion.errors.full_messages.join(', ') %>
<% end %>
<%= form_with(model: promotion, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :name%>
    <%= form.text_field :name,class:'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description,class:'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :code %>
    <%= form.text_field  :code %>
  </div>
  <div class="form-group">
    <%= form.label :discount_rate %>
    <%= form.text_field :discount_rate %>
  </div>

  <% if promotion.coupons.empty? %>
    <div class="form-group">
      <%= form.label :coupon_quantity %>
      <%= form.text_field  :coupon_quantity %>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :expiration_date %>
    <%= form.date_field  :expiration_date %>
  </div>

  <div class="form-group">
    <%= form.collection_check_boxes :product_category_ids, @product_categories, :id, :name %>
  </div>

  <div class="actions">
    <%= form.submit button_submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/promotions/edit.html.erb
<h1>Edit Promotion</h1>
<%= render 'form',{ promotion:@promotion,button_submit:'Enviar' }  %>

app/views/promotions/index.html.erb
<% if @promotions.blank? %>
  <div class="warning">Nenhuma promoção cadastrada</div>
<% else %>
  <dl>
    <% @promotions.each do |promotion| %>
      <dt>Nome: </dt>
      <dd><%= link_to promotion.name, promotion %></dd>
      <dt>Descrição</dt>
      <dd><%=promotion.description%></dd>
      <dt>Porcentagem de Desconto</dt>
      <dd><%=number_to_percentage promotion.discount_rate, precision:2, separator: ','%></dd>
    <% end %>
  </dl>
<% end %>
<%= link_to 'Registrar uma promoção', new_promotion_path %>
<%= link_to 'Voltar', root_path %>

app/views/promotions/new.html.erb
<h1>New Promotion</h1>
<%= render 'form',{ promotion:@promotion,button_submit:'Criar promoção' }  %>

app/views/promotions/show.html.erb
<% if flash.notice %>
  <%= flash.notice %>
<% end %>
<%= link_to 'Voltar', promotions_path %>

<p>
  <strong>Nome:</strong>
  <%= @promotion.name %>
</p>

<p>
  <span> Cadastrada por: <%= @promotion.user.email %></span>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @promotion.description %>
</p>

<p>
  <strong>Porcentagem de Desconto:</strong>
  <%= number_to_percentage @promotion.discount_rate,precision:2, separator: ',' %>
</p>

<p>
  <strong>Código do Cupom:</strong>
  <%= @promotion.code %>
</p>

<p>
  <strong>Data de término:</strong>
  <%= @promotion.expiration_date.strftime('%d/%m/%Y') %>
</p>

<p>
  <strong>Quantidade de cupom:</strong>
  <%= @promotion.coupon_quantity %>
</p>
<p>
  <% if @promotion.approved? %>
    <span>Status: Aprovada</span>
  <% end %>
</p>


<% if current_user != @promotion.user %>
  <%= link_to 'Aprovar Promoção', approve_promotion_path, method: :post %>
<% end %>

<% if @promotion.coupons.count == 0 %>
  <%= link_to 'Gerar cupons', generate_coupons_promotion_path(@promotion), method: :post%>
<% end %>

<%= link_to 'Editar', edit_promotion_path(@promotion) %>
<%= link_to 'Apagar', promotion_path(@promotion), method: :delete, data:{confirm:'Are you sure you want to delete?'}%>

<% @promotion.coupons.each do |coupon|  %>
  <div id="coupon-<%= coupon.id %>">
    <span><%= coupon.code %> (<%= t(coupon.status) %>)</span>
    <% if coupon.active? %>
      <%= link_to 'Inativar', inactivate_coupon_path(coupon), method: :post %>
    <% end %>
  </div>
<% end %>

<% if @promotion.photo.attached? %>
  <h2>Foto</h2>
  <%= image_tag @promotion.photo %>
<% end %>

<h2>Categorias de Produtos</h2>

<% @promotion.product_categories.each do |pc| %>
  <%= pc.name %> - <%= pc.code %>
<% end %>